[package]
name = "kmeans"
version = "0.2.0"
authors = ["Markus Ebner <hiwatari.seiji@gmail.com>"]
edition = "2018"
description = "Small and fast library for k-means clustering calculations."
repository = "https://github.com/seijikun/kmean-rs"
readme = "README.md"
license = "Apache-2.0"
keywords = ["kmeans", "k-means", "means", "cluster", "clustering"]
categories = ["algorithms", "science"]
exclude = ["examples/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
packed_simd = "0"
rayon = "1"
rand = "0"
num = "0"

[patch.crates-io]
packed_simd = { git = "https://github.com/rust-lang-nursery/packed_simd.git", branch = "master" }

[lib]
name = "kmeans"
path = "src/lib.rs"

[[example]]
name = "lloyd"
path = "examples/lloyd.rs"

[[example]]
name = "minibatch"
path = "examples/minibatch.rs"

[[example]]
name = "status_events"
path = "examples/status_events.rs"
